exclude: '^$'
fail_fast: false

repos:
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
    hooks:
    -  id: commitizen
       stages:
       - commit-msg

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
        exclude: .gitlab-ci.yml

-   repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.21
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
      - id: shellcheck
      - id: gofmt
      - id: golint
